Report curl exit codes

diff --git a/htmlios b/htmlios
--- a/htmlios
+++ b/htmlios
@@ -58,9 +58,10 @@ else
 			[[ "${labels// ${monitors[$i]} }" == "$labels" ]] && continue
 
 		curl --fail --compressed -nsLk "${monitors[$((i + 2))]}" >"$workdir"/data
-		if (( $? != 0 ))
+		ret=$?
+		if (( ret != 0 ))
 		then
-			echo "htmlios: Fetching ${monitors[$i]} failed." >&2
+			echo "htmlios: Fetching ${monitors[$i]} failed, curl error $ret" >&2
 			continue
 		fi
 
diff --git a/textios b/textios
--- a/textios
+++ b/textios
@@ -37,19 +37,22 @@ do
 	echo "Fetching $suff..."
 	case ${monitors[$((i + 1))]} in
 		icinga)
-			curl --compressed -nsLk "${monitors[$((i + 2))]}" |
+			curl --fail --compressed -nsLk "${monitors[$((i + 2))]}" |
 				sed 1d | textios-csv_to_editable "$filters" |
 				{ (( onlyhosts )) && textios-onlyhosts || cat; } \
 					>/tmp/textios-"$suff"
+			ret=${PIPESTATUS[0]}
 			;;
 		nagios)
-			curl --compressed -nsLk "${monitors[$((i + 2))]}" |
+			curl --fail --compressed -nsLk "${monitors[$((i + 2))]}" |
 				textios-nagios_to_csv |
 				sed 1d | textios-csv_to_editable "$filters" |
 				{ (( onlyhosts )) && textios-onlyhosts || cat; } \
 					>/tmp/textios-"$suff"
+			ret=${PIPESTATUS[0]}
 			;;
 	esac
+	(( ret != 0 )) && echo "Failed, curl error $ret" >&2
 done
 
 vim -o /tmp/textios-*
