textios: Add a "finished" for each label
Since locations are fetched in parallel now, it's a bit hard to tell
where textios got stuck if one location responds slowly or not at all.

diff --git a/textios b/textios
--- a/textios
+++ b/textios
@@ -47,7 +47,12 @@ do
 					{ (( onlyhosts )) && textios-onlyhosts || cat; } \
 					>/tmp/textios-"$suff"
 				ret=${PIPESTATUS[0]}
-				(( ret != 0 )) && echo "$suff failed, curl error $ret" >&2
+				if (( ret == 0 ))
+				then
+					echo "$suff finished"
+				else
+					echo "$suff failed, curl error $ret" >&2
+				fi
 			) &
 			;;
 		nagios)
@@ -58,7 +63,12 @@ do
 					{ (( onlyhosts )) && textios-onlyhosts || cat; } \
 					>/tmp/textios-"$suff"
 				ret=${PIPESTATUS[0]}
-				(( ret != 0 )) && echo "$suff failed, curl error $ret" >&2
+				if (( ret == 0 ))
+				then
+					echo "$suff finished"
+				else
+					echo "$suff failed, curl error $ret" >&2
+				fi
 			) &
 			;;
 	esac
