Reworked textios to query JSON output from Icinga
Currently broken:

	- Nagios
	- htmlios

The first URL in ~/.textiosrc has changed:

	monitors=(
		foo
		icinga
		'https://your.icinga.example/cgi-bin/icinga/status.cgi'
		'https://your.icinga.example/cgi-bin/icinga/cmd.cgi'

		...
	)

diff --git a/textios b/textios
--- a/textios
+++ b/textios
@@ -8,23 +8,32 @@ fi
 
 . ~/.textiosrc
 
-filters='CRITICAL,UNKNOWN'
-onlyhosts=0
-softstates=0
-while getopts awhs name
+filters_service='CRITICAL,UNKNOWN'
+filters_host='DOWN,UNREACHABLE'
+only_hosts=0
+show_soft=0
+show_acked=0
+show_downtime=0
+while getopts awhSAD name
 do
 	case $name in
 		a)
-			filters=
+			filters_service=
 			;;
 		w)
-			filters='WARNING,CRITICAL,UNKNOWN'
+			filters_service='WARNING,CRITICAL,UNKNOWN'
 			;;
 		h)
-			onlyhosts=1
+			only_hosts=1
 			;;
-		s)
-			softstates=1
+		S)
+			show_soft=1
+			;;
+		A)
+			show_acked=1
+			;;
+		D)
+			show_downtime=1
 			;;
 	esac
 done
@@ -42,33 +51,39 @@ do
 	case ${monitors[$((i + 1))]} in
 		icinga)
 			(
-				curl --fail --compressed -nsLk "${monitors[$((i + 2))]}" |
-					sed 1d | textios-csv_to_editable "$filters" "$softstates" |
-					{ (( onlyhosts )) && textios-onlyhosts || cat; } \
-					>/tmp/textios-"$suff"
-				ret=${PIPESTATUS[0]}
-				if (( ret == 0 ))
-				then
-					echo "$suff finished"
-				else
-					echo "$suff failed, curl error $ret" >&2
-				fi
+				workdir=$(mktemp -d)
+				(
+					cd "$workdir"
+					url=${monitors[$((i + 2))]}
+					(
+						curl --fail --compressed -nsLk \
+							"$url/?style=hostdetail&jsonoutput" \
+							>hosts.json ||
+							echo "Could not fetch hosts: $url" >&2
+					) &
+					(
+						curl --fail --compressed -nsLk \
+							"$url/?host=all&style=detail&jsonoutput" \
+							>services.json ||
+							echo "Could not fetch services: $url" >&2
+					) &
+					wait
+					textios-icinga_to_editable \
+						"$filters_service" \
+						"$filters_host" \
+						"$only_hosts" \
+						"$show_soft" \
+						"$show_acked" \
+						"$show_downtime" \
+						>/tmp/textios-"$suff"
+				)
+				rm -Rf "$workdir"
 			) &
 			;;
 		nagios)
 			(
-				curl --fail --compressed -nsLk "${monitors[$((i + 2))]}" |
-					textios-nagios_to_csv |
-					sed 1d | textios-csv_to_editable "$filters" "$softstates" |
-					{ (( onlyhosts )) && textios-onlyhosts || cat; } \
-					>/tmp/textios-"$suff"
-				ret=${PIPESTATUS[0]}
-				if (( ret == 0 ))
-				then
-					echo "$suff finished"
-				else
-					echo "$suff failed, curl error $ret" >&2
-				fi
+				echo "NAGIOS CURRENTLY NOT SUPPORTED" >&2
+				touch /tmp/textios-"$suff"
 			) &
 			;;
 	esac
